/* eslint-disable import/prefer-default-export */
export const Experiences = [
  {
    logo: 'groupado.png',
    companyName: 'Groupado',
    website: 'https://www.groupado.com/en',
    duration: 'Sep 2021 - Present',
    role: 'Senior Fullstack js developer',
    tasks: [
      'Contribution to the structuring of the project',
      'Integration of different payment methods (Paypal, Checkout...) ',
      'Creation of generic components with NextJS',
      'Implementation of unit tests with React testing library.',
    ],
    environments: [
      'Ubuntu 18.04',
      'NextJS',
      'SSR',
      'Rtl',
      'Typescript',
      'Sass',
      'Docker',
      'Git',
      'Git-flow',
      'Gitlab',
      'Agile / Scrum,',
    ],
  },
  {
    logo: 'simplon.jpg',
    companyName: 'Simplon',
    website: 'https://simplon.co/',
    duration: 'Feb 2020 - Aug 2021',
    role: 'Lead web development & fullstack js developer',
    tasks: [
      'he capture of needs and study of the existing',
      'Development of the front-office and back-office part with React JS ',
      'build the rest API with Express js',
      'Implementation of unit tests with Jest',
      'Technical documentation with Swagger'
    ],
    environments: [
      'Ubuntu 18.04',
      'NextJS',
      'Context',
      'API',
      'SSR',
      'Jest',
      'Typescript',
      'NodeJS',
      'ExpressJS',
      'Git',
      'Bitbucket',
      'Agile/Scrum',
    ],
  },
  {
    logo: 'lightency.jpg',
    companyName: 'Lightency',
    website: 'https://lightency.io/#/',
    duration: 'Apr 2019 - Jan 2020 ',
    role: 'Fullstack JS & Blockchain developer',
    tasks: [
      'Participation in the identification and design phase',
      'Development of the back office part with React JS / Redux',
      ' Development of statistical components with ChartJs',
      'Handling issues in real-time',
      'Creation of microservices NodeJS connected to a smart blockchain microgrid',
    ],
    environments: [
      'Ubuntu 18.04',
      'React JS',
      'Typescript',
      'Sass',
      'Blockchain',
      'Hyperledger Fabric',
      'Agile / Scrum',
      'Bitbucket ',
      'Git,',
    ],
  },
]
